### ISSUE TITLE
User can submit a match with same team. 

### ISSUE THREAD

**Issue by anhtqeth** [anhtqeth/fantasy-fooballs#5]
This result in an error for showing match teams in index

**Comment by brianw921** [comment]
Working on the matches now, but I fixed other issues regarding your models, migrations, and seed file. Your migrations need to be in order. For example, in order to "add match to games", it needs to go after your "create matches".

**Comment by anhtqeth** [comment]
Thanks for your interest! And yes, the migration caused some problems when I deployed this to Heroku. I also made some changes after that
This is actually a quick exercise to review my Rails experience. I just closed it via the latest commit.

**Comment by brianw921** [comment]
Can you please accept it I’m trying to score some points for Hacktoberfest
